version: "3.1"

services:
    mailhog:
      image: mailhog/mailhog:latest
      container_name: mailhog
      environment:
        - VIRTUAL_HOST=mail.test-web.com
        - VIRTUAL_PORT=8025
      networks:
        - nginx-proxy

    mariadb:
      image: mariadb
      container_name: mariadb
      restart: always
      env_file:
        - ./docker.env
      networks:
        - nginx-proxy

    adminer:
      image: adminer
      container_name: adminer
      restart: always
      environment:
        - VIRTUAL_HOST=db.test-web.com
      ports:
        - 8080:8080
      networks:
        - nginx-proxy

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /var/www/web
      environment:
        - VIRTUAL_HOST=test-web.com
      volumes:
          - .:/var/www/web
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8002:80"
      networks:
        - nginx-proxy

    php-fpm:
      build: docker/php-fpm
      container_name: php-fpm
      working_dir: /var/www/web
      volumes:
        - .:/var/www/web
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
